name: Androweed kernel

on:
  workflow_dispatch:
  push:
    branches: [ OSS-RUI2-NO-KSU ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v2
     
    - name: Checkout zipper
      uses: actions/checkout@v2
      with:
        repository: ucip123/AnyKernel3
        path: zipper

    - name: vendor
      uses: actions/checkout@v2
      with:
        repository: ucip123/realme_C25_C25s_narzo-50A-AndroidT-vendor-source
 
    - name: krenel maybe
      uses: actions/checkout@v2
      with:
        repository: ucip123/android_kernel_realme_even

    - name: mulai membuil krenel anda🗿
      uses: ucip123/android-kernel-actions@master
      id: build
      env:
        NAME: KernelAbalAbal
      with:
        arch: arm64
        compiler:  aosp-clang/master/clang-r498229b
        defconfig: k68v1_64_k419_defconfig
        image: Image.gz-dtb

    - name: ngerilis built ke gc guwa
      uses: appleboy/telegram-action@master
      with:
        to: ${{ -1001850488353 }}
        token: ${{ secrets.TG_BOTOKEN }}
        message: Kernel nya udh jadi
                ${{ steps.build.outputs.elapsed_time }} detik.
        document: ${{ steps.build.outputs.outfile }}
